name: Pylint

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Checkout PyTorch
      uses: actions/checkout@master
    - name: Install flake8
      run: pip install flake8
    - name: Run flake8
      uses: suo/flake8-github-action@releases/v1
      with:
        checkName: 'flake8_py3'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pylint
        pip install pyGitHub
    - name: Analysing the code with pylint
      run: |
        find . -type f -name "*.py" | xargs pylint --exit-zero
        